apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: w5fgn10gt-java-springboot
  janus-idp.io/tekton: w5fgn10gt-java-springboot
  backstage.io/kubernetes-id: w5fgn10gt-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: w5fgn10gt-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
